fix gf tpl command
gogf/gf-cli pull request #145
Opened 2022-01-16 05:06 UTC by astraw99

1. add gf tpl cmd;
2. go mod tidy go.sum;
3. add sql type;

2022-01-16 16:22 UTC, gqcn requested changes

2022-01-16 16:22 UTC, gqcn commented on internal/cmd/cmd_tpl.go
> +	cTplSupportValuesFilePattern = `*.json,*.xml,*.yaml,*.yml,*.toml,*.ini,*.sql`
这个是变量文件类型的格式，因此不支持`*.sql`

2022-01-17 03:37 UTC, astraw99 commented on internal/cmd/cmd_tpl.go
> +	cTplSupportValuesFilePattern = `*.json,*.xml,*.yaml,*.yml,*.toml,*.ini,*.sql`
好的，明白了，这个是 values 支持的文件类型~

2022-01-17 03:42 UTC, astraw99 commented on internal/cmd/cmd_tpl.go
> +	cTplSupportValuesFilePattern = `*.json,*.xml,*.yaml,*.yml,*.toml,*.ini,*.sql`
Updated, PTAL thanks.

2022-01-23 15:33 UTC, merged